### ISSUE TITLE
Conversion result error

### ISSUE THREAD

**Issue by wll8** [myadzel/saz2har#6]
## Before conversion
<img width="1020" alt="WX20190907-132319@2x" src="https://user-images.githubusercontent.com/28223260/64470250-d87c1c00-d172-11e9-8e3f-cf8149d6ee66.png">

## After conversion
<img width="1157" alt="WX20190907-132333@2x" src="https://user-images.githubusercontent.com/28223260/64470255-e7fb6500-d172-11e9-95a6-ffb2bb1b9a6a.png">

**Comment by myadzel** [comment]
You need to attach the original SAZ and the result in HAR, and describe the problem.

So far I see JSON, which has nothing to do with SAZ to HAR conversion.
